version: '3'

services:
  node_service:
    build: ./
    tty: true
    volumes:
      - ./:/app
  postgres_service:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db